### ISSUE TITLE
python: dmtxdecodescheme.c:115: PushOutputWord: Assertion `value >= 0 && value < 256' failed.

### ISSUE THREAD

**Issue by gdwu1427** [NaturalHistoryMuseum/pylibdmtx#50]
Hello！@
       when I test the piture below, there is an error, can you tell me how to optimize the code, thank you!
      python: dmtxdecodescheme.c:115: PushOutputWord: Assertion `value >= 0 && value < 256' failed.
    
![55](https://user-images.githubusercontent.com/52492003/63818987-1a88af00-c976-11e9-882b-187444476354.jpg)

> 

> 

> 

>

**Comment by gdwu1427** [comment]
This issue has been resolved，thank you！

**Comment by markemus** [comment]
Resolved? This issue is not resolved, I still have it :) Please post your solution before closing the issue.

**Comment by TravisTianqing** [comment]
> Hello！@
> when I test the piture below, there is an error, can you tell me how to optimize the code, thank you!
> python: dmtxdecodescheme.c:115: PushOutputWord: Assertion `value >= 0 && value < 256' failed.
> 
> ![55](https://user-images.githubusercontent.com/52492003/63818987-1a88af00-c976-11e9-882b-187444476354.jpg)
> 
can you share you solution?
> 
> > 
> 
> > 
> 
> >

**Comment by EmrahErden** [comment]
Please reopen this issue

**Comment by ninafiona** [comment]
I still have this issue too, even though my input image has the maximum value 255 and minimum 0.

**Comment by xjpf** [comment]
have same
